# Site Settings
title: ""
name: Joe Ledford
description: Data Science Senior at American University
url: "https://joe-ledford-04.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "sunrise" # options: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

# Site Author
author:
  name: Joe Ledford
  bio: "Data Science Senior at American University"
  location: "Washington, D.C."
  avatar: "/assets/images/Headshot.jpg"

  links:
    - label: "Github
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joe-ledford-04"
  
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/joseph-ledford04"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

