# Site Settings
title: ""
name: Joe Ledford
description: Data Science Senior at American University
url: "https://joe-ledford-04.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "sunrise" # options: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

# Site Author
author:
  name: Joe Ledford
  avatar: "/assets/images/headshot.jpg"
  bio: "Data Science Senior at American University"
  location: "Washington, DC"
  github: "joe-ledford-04"
  linkedin: "joseph-ledford04"
      
# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true



